[package]
name = "vgpu_unlock-rs"
version = "1.0.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.102"
serde = { version = "1.0.130", features = ["derive"] }
toml = "0.5.8"
