[package]
name = "vgpu_unlock-rs"
version = "2.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
ctor = "0.1.21"
libc = "0.2.102"
parking_lot = "0.12.0"
serde = { version = "1.0.130", features = ["derive"] }
toml = "0.5.8"
